### PR TITLE
Update `TryGetCollectionCount` to use `TryGetNonEnumeratedCount` from .net6.0+ corelib 

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Comment by Arithmomaniac** [comment]
IIRC, stdlib offers no optimizations for `IReadOnly*`, so relying on anything from it is technically a breaking change

**Comment by viceroypenguin** [comment]
Yeah- figured that out with failing tests. Haven't decided what to do yet. Might do: 
```csharp
source.TryGetNonEnumeratedCount(out var count) ? out count : 
source is IReadOnlyCollection<TSource> iroc ? out iroc.Count :
null
```

**Comment by Arithmomaniac** [comment]
That would work. You could also remove special `IReadOnly*` handling entirely for all versions (ironic for me to suggest that, since I added it to MoreLinq to begin with... but I don't see a reason to handle it if stdlib has repeatedly and explicitly decided not to).

**Comment by viceroypenguin** [comment]
@Arithmomaniac I removed support for `IReadOnlyCollection` in #132. Technically a breaking change, but per corelib, I don't expect `IReadOnlyCollection` is common without also implementing `ICollection`. Given the lack of use of this library, number of affected users should be negligible.

**Pull request merged**
