### PR TITLE
fix to simplify randomsetsetimpl code#540

### PR DESCRIPTION
**Pull request by kthurman59**

### CODE REVIEW

**Comment by kthurman59** [comment]
My PR appears to solve this issue code#540

**Comment by viceroypenguin** [comment]
Thanks! You're on the right track. However, a proper solution will not need the `seeder` parameter at all. Consider what the purpose of the `seeder` method is, and why it is not needed.

**Comment by kthurman59** [comment]
Ahhhh!  That makes sense!  Let me take another crack at this.

**Comment by kthurman59** [comment]
Took away the 'seeder' parameter as I shouldn't have added it in.  Please let me know if I can add or refactor any part of this.

**Comment by viceroypenguin** [comment]
I'm sorry, your work does not even build, so I am rejecting this PR. Please review #568 for an example of a proper change. I encourage you to try again with another issue.

**Pull request closed without merging**
